site_name: PodPIX
repo_url: https://github.com/podpix/podpix.github.io
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - footnotes
nav:
  - "Sobre": 
    - index.md
    - institucional.md
    - imprensa.md
  - CONTRIBUTING.md
  - SUPPORT.md 